=== mathimathy/Boa/exemples/graphic/posGrid/ext/gui.dtd
<!ELEMENT App (Frame+)>
<!ATTLIST App size CDATA #REQUIRED>
<!ATTLIST App title CDATA #REQUIRED>
<!ELEMENT Frame (input|label|button)*>
<!ATTLIST Frame pos (pack|grid) #REQUIRED>
<!ATTLIST Frame x CDATA #IMPLIED>
<!ATTLIST Frame y CDATA #IMPLIED>
<!ELEMENT input EMPTY>
<!ATTLIST input text CDATA #REQUIRED>
<!ATTLIST input id ID #REQUIRED>
<!ATTLIST input x CDATA #IMPLIED>
<!ATTLIST input y CDATA #IMPLIED>
<!ELEMENT label EMPTY>
<!ATTLIST label text CDATA #REQUIRED>
<!ATTLIST label id ID #IMPLIED>
<!ATTLIST label x CDATA #IMPLIED>
<!ATTLIST label y CDATA #IMPLIED>
<!ELEMENT button EMPTY>
<!ATTLIST button text CDATA #REQUIRED>
<!ATTLIST button action CDATA #REQUIRED>
<!ATTLIST button id ID #REQUIRED>
<!ATTLIST button x CDATA #IMPLIED>
<!ATTLIST button y CDATA #IMPLIED>

=== mathimathy/Boa/exemples/calculette/ext/app.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE App SYSTEM "gui.dtd">
<App size="1280x720" title="Calculette">
    <Frame pos="grid" x="0" y="0">
        <label text="{pop}" id="display" x="0" y="0"/>
    </Frame>
    <Frame pos="grid" x="0" y="1">
        <button text="7" action="src/button/b7.b" id="b7" x="0" y="0" />
        <button text="8" action="src/button/b8.b" id="b8" x="1" y="0" />
        <button text="9" action="src/button/b9.b" id="b9" x="2" y="0" />
        <button text="+" action="src/button/badd.b" id="badd" x="3" y="0" />
        <button text="4" action="src/button/b4.b" id="b4" x="0" y="1" />
        <button text="5" action="src/button/b5.b" id="b5" x="1" y="1" />
        <button text="6" action="src/button/b6.b" id="b6" x="2" y="1" />
        <button text="-" action="src/button/bminus.b" id="bminus" x="3" y="1" />
        <button text="1" action="src/button/b1.b" id="b1" x="0" y="2" />
        <button text="2" action="src/button/b2.b" id="b2" x="1" y="2" />
        <button text="3" action="src/button/b3.b" id="b3" x="2" y="2" />
        <button text="*" action="src/button/btimes.b" id="btimes" x="3" y="2" />
        <button text="." action="src/button/bpoint.b" id="bpoint" x="0" y="3" />
        <button text="0" action="src/button/b0.b" id="b0" x="1" y="3" />
        <button text="=" action="src/button/bequal.b" id="bequal" x="2" y="3" />
        <button text="/" action="src/button/bdivide.b" id="bdivide" x="3" y="3" />
    </Frame>
</App>
